exports.ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
exports.ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
exports.ADD_TODO_STARTED = "ADD_TODO_STARTED";
exports.DELETE_TODO = "DELETE_TODO";

exports.LOADING_TOP_PLAYERS = "LOADING_TOP_PLAYERS";
exports.LOADED_TOP_PLAYERS = "LOADED_TOP_PLAYERS";
exports.LOAD_TOP_PLAYERS_FAILURE = "LOAD_TOP_PLAYERS_FAILURE";

exports.LOADING_ALL_PLAYERS = "LOADING_ALL_PLAYERS";
exports.LOADED_ALL_PLAYERS = "LOADED_ALL_PLAYERS";
exports.LOAD_ALL_PLAYERS_FAILURE = "LOAD_ALL_PLAYERS_FAILURE";

exports.ADDING_PLAYER = "ADDING_PLAYER";
exports.ADDED_PLAYER = "ADDED_PLAYER";
exports.ADD_PLAYER_FAILURE = "ADD_PLAYER_FAILURE";

exports.SUCCESS_NOTIFICATION_START = "SUCCESS_NOTIFICATION_START";
exports.SUCCESS_NOTIFICATION_END = "SUCCESS_NOTIFICATION_END";
exports.ERROR_NOTIFICATION_START = "ERROR_NOTIFICATION_START";
exports.ERROR_NOTIFICATION_END = "ERROR_NOTIFICATION_END";

exports.LOADING_GAME_RESULTS = "LOADING_GAME_RESULTS";
exports.LOADED_GAME_RESULTS = "LOADED_GAME_RESULTS";
exports.LOAD_GAME_RESULTS_FAILURE = "LOAD_GAME_RESULTS_FAILURE";

exports.ADDING_GAME_RESULT = "ADDING_GAME_RESULT";
exports.ADDED_GAME_RESULT = "ADDED_GAME_RESULT";
exports.ADD_GAME_RESULT_FAILURE = "ADD_GAME_RESULT_FAILURE";